f-django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),
    path('aboutus/', views.aboutus_view,name='about'),
    path('contactus/', views.contactus_view, name='contactus'),

    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),

    
]

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block metatitle %}SUPER POWER-PAC{% endblock metatitle %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel2/assets/owl.theme.default.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="page-holder">
      {% include 'navbar.html' %}

      {% block content %}

      {% endblock content %}

      {% block payment-gateway %}{% endblock payment-gateway %}
      
      {% include 'footer.html' %}
      {% include 'scripts.html' %}

templates/footer.html
<footer style="margin-top: 10">
  <div class="container">
      <div class="row">
          <div class="col-md-5">
              <div class="about-veno">
                  
                  <p>PRIVATISE YOUR PRIVACY,KEEP IT SAFE.</p>
                   <ul class="social-icons">
                      <li>
                          <a href="#"><i class="fa fa-facebook"></i></a>
                          <a href="#"><i class="fa fa-twitter"></i></a>
                          <a href="#"><i class="fa fa-linkedin"></i></a>
                          <a href="#"><i class="fa fa-rss"></i></a>
                          <a href="#"><i class="fa fa-dribbble"></i></a>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-md-4">
              <div class="useful-links">
                  <div class="footer-heading">
                      <h4>Useful Links</h4>
                  </div>
                  <div class="row">
                      
                  </div>
              </div>
          </div>
          <div class="col-md-3">
              <div class="contact-info">
                  <div class="footer-heading">
                      <h4>Contact Information</h4>
                  </div>
                  <p>SUPER POWER-PAC Provides You with the Best Quality Of The Support Services.</p>
                  <ul>
                      <li><span>Phone:</span><a href="#">+234 07066886999</a></li>
                      <li><span>Email:</span><a href="#">iwujichimankpafranklin@gmail.com</a></li>
                      <li><span>Address:</span><a href="#">Nigeria</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" type="text/javascript"></script>
<footer style=background-color:rgb(248,171,4); class=" text-white">
    <div class="container py-4">
      <div class="row py-5">
        <div class="col-md-4 mb-3 mb-md-0">
          <h6 class="text-uppercase mb-3">Customer services</h6>
          <ul class=" text-white">
            <li><a class="footer-link text-white" href="/contactus">Help &amp; Contact Us</a></li>
            <li><a class="footer-link text-white" href="/">Online Stores</a></li>
            <li><a class="footer-link text-white" href="#">Terms &amp; Conditions</a></li>
          </ul>
        </div>
        <div class="col-md-4 mb-3 mb-md-0">
          <h6 class="text-uppercase mb-3">Company</h6>
          <ul class=" text-white">
            <li><a class="footer-link text-white" href="/aboutus">What We Do/ABOUT</a></li>
            <li><a class="footer-link text-white" href="{% url 'store:login' %}">Available Services</a></li>
            <li><a class="footer-link text-white" href="#">Latest Posts</a></li>

          </ul>
        </div>
        <div class="col-md-4">
          <h6 class="text-uppercase mb-3">Social media</h6>
          <ul class=" text-white">
            <li><a href="https://facebook.com/iwuji.franklin.9/" class="footer-link text-white"><h5>FACEBOOK</h5></a></li>
            <li><a href="https://api.whatsapp.com/send?phone=09035757001&text=Hello%20Sumit.%0d%0aHow%20are%20you%20%3f%0d%0aI%20came%20from%20your%20website.&source=&data=#" class="footer-link text-white"><h5>WHATSAPP</h5></a></li>
            <li><a href="https://instagram.com/Alexandria96" class="footer-link text-white"><h5>INSTAGRAM</h5></a></li>
            <li><a href="#" class="footer-link text-white"><h5>TWITTER</h5></a></li>                
          </ul>
        </div>
      </div>
      <div class="border-top pt-4" style="border-color: #030303 !important">
        <div class="row">
          <div class="col-lg-6">
            <h3><p class="small text-white">&copy; 2021 All rights reserved.</p></h3>
          </div>
          <div class="col-lg-6 text-lg-right">
            </h3><p class="small text-white">CREDITS TO> <a class="text-white reset-anchor" href="https://www.youtube.com/vijaythapa" target="_blank">SUPER POWER-PAC software engineers</a></p></h3>
          </div>
        </div>
      </div>
    </div>
</footer>

templates/navbar.html
{% load static %}

<!-- navbar-->
      <header style=background-color:rgb(47,255,6); class="header">
        <div class="logo" >

          <img src="{% static 'img/FB_IMG_16178779706163313.jpg' %}" href="{% url 'store:home' %}" alt="Super POWER-PAC Logo" width="200" height="99">
        </div>        
        <div class="container px-0 px-lg-3">
          </div>
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'store:home' %}"><span class="font-weight-bold text-uppercase text-dark"><h1>SUPER POWER-PAC</h1></span></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <!-- Link--><a class="nav-link active" href="{% url 'store:home' %}"><h4>HOME</h4></a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><h4>CATEGORY</h4></a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}"><h6>{{cat_menu.title}}</h6></a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories' %}"><h6>ALL CATEGORIES</h6></a>
                    
                </li>
                
                <li class="nav-item">
                  <!-- Link--><a class="nav-link" href="/contactus"><h4>CONTACT</h4></a>
                </li>
              </ul>
              <ul class="navbar-nav ml-auto"> 
                {% if request.user.is_authenticated %}           
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i><h4>CART-ITEMS</h4><small class="text-gray"><h4>({{cart_items.count}})</h4></small></a></li>
                  <li class="nav-item"><a class="nav-link" href="#"> <i class="far fa-heart mr-1"></i><small class="text-gray"> (0)</small></a></li>
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="fas fa-user-alt mr-1 text-gray"></i><h4> Account</h4></a></li> {% endcomment %}

                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i><h4>My Account</h4></a></a>
                  
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}"><h6>PROFILE</h6></a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}"><h6>CART</h6></a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}"><h6>ORDERS</h6></a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:password-change' %}"><h6>Change-Password</h6></a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:about' %}"><h6>ABOUT US</h6></a>

                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:logout' %}"><h6>LOG OUT</h6></a>
                    
                </li>
                {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:about' %}"><h6>ABOUT</h6></a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}"><h5>LOGIN</h5></a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:register' %}"><h6>CREATE ACCOUNT</h6></a></li>
                {% endif %}   
              </ul>
            </div>
          </nav>
        </div>
      </header>

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>

      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>